---
pygments: true
markdown: rdiscount
exclude: ["Gemfile", "README.md"]
title: direnv - unclutter your .profile
production_url : http://direnv.net/
author:
  name: Jonas Pfenniger
  email: jonas@pfenniger.name
